const characters = [
  {
    name: "Jon Snow",
    house: "Stark",
    gender: "Male",
    origin: "North",
    age: 24,
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/jon.jpg",
    status: "alive",
    weapon: "Valyrian steel sword",
    role: "Nights Watch"
  },
  {
    name: "Daenerys Targaryen",
    house: "Targaryen",
    gender: "Female",
    origin: "Essos",
    age: 23,
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/daenerys.jpg",
    status: "dead",
    weapon: "Dragons",
    role: "Ruler"
  },
  {
    name: "Tyrion Lannister",
    house: "Lannister",
    gender: "Male",
    origin: "Westerlands",
    age: 38,
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/tyrion.jpg",
    status: "alive",
    weapon: "Wit",
    role: "Highborn"
  },
  {
    name: "Arya Stark",
    house: "Stark",
    gender: "Female",
    age: 18,
    origin: "North",
    religion: "Many-Faced God",
    first_seen: "Season 1",
    image: "ımage/arya.jpg",
    status: "alive",
    weapon: "Sword",
    role: "Assassin"
  },
  {
    name: "Cerenna Lannister",
    house: "Lannister",
    gender: "Female",
    age: 20,
    origin: "Westerlands",
    religion: "Old Gods",
    first_seen: "Book",
    image: "ımage/cerenna.jpg",
    status: "alive",
    weapon: "None",
    role: "Lady"
  },
  {
    name: "Olenna Tyrell",
    house: "Tyrell",
    gender: "Female",
    age: 74,
    origin: "Reach",
    religion: "None",
    first_seen: "Season 3",
    image: "ımage/olenna.jpg",
    status: "dead",
    weapon: "Wit",
    role: "Lady"
  },
  {
    name: "Cersei Lannister",
    house: "Lannister",
    gender: "Female",
    age: 44,
    origin: "Westerlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/cersei.jpg",
    status: "dead",
    weapon: "Manipulation",
    role: "Ruler"
  },
  {
    name: "Robb Stark",
    house: "Stark",
    gender: "Male",
    age: 17,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/robb.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Lord"
  },
  {
    name: "Jamie Lannister",
    house: "Lannister",
    gender: "Male",
    age: 45,
    origin: "Westerlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/jamie.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Knight"
  },
  {
    name: "Sansa Stark",
    house: "Stark",
    gender: "Female",
    age: 21,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/sansa.jpg",
    status: "alive",
    weapon: "Politics",
    role: "Lady"
  },
  {
    name: "Bran Stark",
    house: "Stark",
    gender: "Male",
    age: 20,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/bran.jpg",
    status: "alive",
    weapon: "Warging",
    role: "Ruler"
  },
  {
    name: "Theon Greyjoy",
    house: "Greyjoy",
    gender: "Male",
    age: 27,
    origin: "Iron Islands",
    religion: "Drowned God",
    first_seen: "Season 1",
    image: "ımage/theon.jpg",
    status: "dead",
    weapon: "Bow",
    role: "Highborn"
  },
  {
    name: "Brienne of Tarth",
    house: "Tarth",
    gender: "Female",
    age: 32,
    origin: "Stormlands",
    religion: "Faith of the Seven",
    first_seen: "Season 2",
    image: "ımage/brienne.jpg",
    status: "alive",
    weapon: "Valyrian steel sword",
    role: "Knight"
  },
  {
    name: "Sandor Clegane",
    house: "Clegane",
    gender: "Male",
    age: 40,
    origin: "Westerlands",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/sandor.jpg",
    status: "dead",
    weapon: "Greatsword",
    role: "Kinght"
  },
  {
    name: "Samwell Tarly",
    house: "Tarly",
    gender: "Male",
    age: 26,
    origin: "Reach",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/samwell.jpg",
    status: "alive",
    weapon: "Knowledge",
    role: "Nights Watch"
  },
  {
    name: "Margaery Tyrell",
    house: "Tyrell",
    gender: "Female",
    age: 26,
    origin: "Reach",
    religion: "Faith of the Seven",
    first_seen: "Season 2",
    image: "ımage/margaery.jpg",
    status: "dead",
    weapon: "Charm",
    role: "Ruler"
  },
  {
    name: "Jorah Mormont",
    house: "Mormont",
    gender: "Male",
    age: 52,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/jorah.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Knight"
  },
  {
    name: "Davos Seaworth",
    house: "Seaworth",
    gender: "Male",
    age: 58,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 2",
    image: "ımage/davos.jpg",
    status: "alive",
    weapon: "Knife",
    role: "Lord"
  },
  {
    name: "Melisandre",
    house: "None",
    gender: "Female",
    age: 400,
    origin: "Asshai",
    religion: "Lord of Light",
    first_seen: "Season 2",
    image: "ımage/melisandre.jpg",
    status: "dead",
    weapon: "Magic",
    role: "Clergy Member"
  },
  {
    name: "Eddard Stark",
    house: "Stark",
    gender: "Male",
    age: 45,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/eddard.jpg",
    status: "dead",
    weapon: "Greatsword",
    role: "Lord"
  },
  {
    name: "Khal Drogo",
    house: "Dothraki",
    gender: "Male",
    age: 30,
    origin: "Essos",
    religion: "Great Stallion",
    first_seen: "Season 1",
    image: "ımage/drogo.jpg",
    status: "dead",
    weapon: "Arakh",
    role: "Ruler"
  },
  {
    name: "Joffrey Baratheon",
    house: "Baratheon",
    gender: "Male",
    age: 19,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/joffrey.jpg",
    status: "dead",
    weapon: "Crossbow",
    role: "Ruler"
  },
  {
    name: "Varys",
    house: "None",
    gender: "Male",
    age: 52,
    origin: "Essos",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/varys.jpg",
    status: "dead",
    weapon: "Information",
    role: "Servant"
  },
  {
    name: "Petyr Baelish",
    house: "Baelish",
    gender: "Male",
    age: 42,
    origin: "Vale of Arryn",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/petyr.jpg",
    status: "dead",
    weapon: "Manipulation",
    role: "Highborn"
  },
  {
    name: "Bronn",
    house: "None",
    gender: "Male",
    age: 44,
    origin: "Riverlands",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/bronn.jpg",
    status: "alive",
    weapon: "Sword",
    role: "Kinght"
  },
  {
    name: "Gendry",
    house: "Baratheon",
    gender: "Male",
    age: 25,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/gendry.jpg",
    status: "alive",
    weapon: "War hammer",
    role: "Lord"
  },
  {
    name: "Missandei",
    house: "None",
    gender: "Female",
    age: 23,
    origin: "Naath",
    religion: "None",
    first_seen: "Season 3",
    image: "ımage/missandei.jpg",
    status: "dead",
    weapon: "None",
    role: "Servant"
  },
  {
    name: "Ygritte",
    house: "Free Folk",
    gender: "Female",
    age: 19,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 2",
    image: "ımage/ygritte.jpg",
    status: "dead",
    weapon: "Bow",
    role: "Warrior"
  },
  {
    name: "Tormund Giantsbane",
    house: "Free Folk",
    gender: "Male",
    age: 48,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 3",
    image: "ımage/tormund.jpg",
    status: "alive",
    weapon: "Axe",
    role: "Warrior"
  },
  {
    name: "Grey Worm",
    house: "None",
    gender: "Male",
    age: 30,
    origin: "Essos",
    religion: "None",
    first_seen: "Season 3",
    image: "ımage/greyworm.jpg",
    status: "alive",
    weapon: "Spear",
    role: "Warrior"
  },
  {
    name: "Stannis Baratheon",
    house: "Baratheon",
    gender: "Male",
    age: 50,
    origin: "Stormlands",
    religion: "Lord of Light",
    first_seen: "Season 2",
    image: "ımage/stannis.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Lord"
  },
  {
    name: "Renly Baratheon",
    house: "Baratheon",
    gender: "Male",
    age: 28,
    origin: "Stormlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/renly.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Lord"
  },
  {
    name: "Shae",
    house: "None",
    gender: "Female",
    age: 25,
    origin: "Essos",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/shae.jpg",
    status: "dead",
    weapon: "Dagger",
    role: "Servant"
  },
  {
    name: "Podrick Payne",
    house: "Payne",
    gender: "Male",
    age: 22,
    origin: "Westerlands",
    religion: "Faith of the Seven",
    first_seen: "Season 2",
    image: "ımage/podrick.jpg",
    status: "alive",
    weapon: "Sword",
    role: "Servant"
  },
  {
    name: "Barristan Selmy",
    house: "Selmy",
    gender: "Male",
    age: 68,
    origin: "Stormlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/barristan.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Knight"
  },
  {
    name: "Hodor",
    house: "None",
    gender: "Male",
    age: 35,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/hodor.jpg",
    status: "dead",
    weapon: "Strength",
    role: "Servant"
  },
  {
    name: "Lyanna Mormont",
    house: "Mormont",
    gender: "Female",
    age: 12,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 6",
    image: "ımage/lyanna.jpg",
    status: "dead",
    weapon: "Words",
    role: "Lady"
  },
  {
    name: "Ellaria Sand",
    house: "Sand",
    gender: "Female",
    age: 38,
    origin: "Dorne",
    religion: "None",
    first_seen: "Season 4",
    image: "ımage/ellaria.jpg",
    status: "alive",
    weapon: "Poison",
    role: "Lady"
  },
  {
    name: "Oberyn Martell",
    house: "Martell",
    gender: "Male",
    age: 42,
    origin: "Dorne",
    religion: "None",
    first_seen: "Season 4",
    image: "ımage/oberyn.jpg",
    status: "dead",
    weapon: "Spear",
    role: "Prince"
  },
  {
    name: "High Sparrow",
    house: "None",
    gender: "Male",
    age: 65,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 5",
    image: "ımage/sparrow.jpg",
    status: "dead",
    weapon: "Faith",
    role: "Clergy Member"
  },
  {
    name: "Jaqen H'ghar",
    house: "None",
    gender: "Male",
    age: 45,
    origin: "Lorath",
    religion: "Many-Faced God",
    first_seen: "Season 1",
    image: "ımage/jaqen.jpg",
    status: "alive",
    weapon: "Poison",
    role: "Assassin"
  },
  {
    name: "Qyburn",
    house: "None",
    gender: "Male",
    age: 60,
    origin: "Westerlands",
    religion: "None",
    first_seen: "Season 3",
    image: "ımage/qyburn.jpg",
    status: "dead",
    weapon: "Science",
    role: "Maester"
  },
  {
    name: "Gregor Clegane",
    house: "Clegane",
    gender: "Male",
    age: 42,
    origin: "Westerlands",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/gregor.jpg",
    status: "dead",
    weapon: "Greatsword",
    role: "Knight"
  },
  {
    name: "Meera Reed",
    house: "Reed",
    gender: "Female",
    age: 20,
    origin: "Neck",
    religion: "Old Gods",
    first_seen: "Season 3",
    image: "ımage/meera.jpg",
    status: "alive",
    weapon: "Bow",
    role: "Highborn"
  },
  {
    name: "Jojen Reed",
    house: "Reed",
    gender: "Male",
    age: 18,
    origin: "Neck",
    religion: "Old Gods",
    first_seen: "Season 3",
    image: "ımage/jojen.jpg",
    status: "dead",
    weapon: "Vision",
    role: "Highborn"
  },
  {
    name: "Roose Bolton",
    house: "Bolton",
    gender: "Male",
    age: 55,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 2",
    image: "ımage/roose.jpg",
    status: "dead",
    weapon: "Dagger",
    role: "Lord"
  },
  {
    name: "Ramsay Bolton",
    house: "Bolton",
    gender: "Male",
    age: 28,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 3",
    image: "ımage/ramsay.jpg",
    status: "dead",
    weapon: "Bow",
    role: "Lord"
  },
  {
    name: "Walder Frey",
    house: "Frey",
    gender: "Male",
    age: 92,
    origin: "Riverlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/walder.jpg",
    status: "dead",
    weapon: "Treachery",
    role: "Lord"
  },
  {
    name: "Lysa Arryn",
    house: "Arryn",
    gender: "Female",
    age: 38,
    origin: "Vale of Arryn",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/lysa.jpg",
    status: "dead",
    weapon: "Poison",
    role: "Lady"
  },
  {
    name: "Robin Arryn",
    house: "Arryn",
    gender: "Male",
    age: 16,
    origin: "Vale of Arryn",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/robin.jpg",
    status: "alive",
    weapon: "Influence",
    role: "Lord"
  },
  {
    name: "Beric Dondarrion",
    house: "Dondarrion",
    gender: "Male",
    age: 35,
    origin: "Stormlands",
    religion: "Lord of Light",
    first_seen: "Season 1",
    image: "ımage/beric.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Highborn"
  },
  {
    name: "Thoros of Myr",
    house: "None",
    gender: "Male",
    age: 48,
    origin: "Myr",
    religion: "Lord of Light",
    first_seen: "Season 3",
    image: "ımage/thoros.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Priest"
  },
  {
    name: "Yara Greyjoy",
    house: "Greyjoy",
    gender: "Female",
    age: 30,
    origin: "Iron Islands",
    religion: "Drowned God",
    first_seen: "Season 2",
    image: "ımage/yara.jpg",
    status: "alive",
    weapon: "Axe",
    role: "Lady"
  },
  {
    name: "Euron Greyjoy",
    house: "Greyjoy",
    gender: "Male",
    age: 48,
    origin: "Iron Islands",
    religion: "Drowned God",
    first_seen: "Season 6",
    image: "ımage/euron.jpg",
    status: "dead",
    weapon: "Axe",
    role: "Lord"
  },
  {
    name: "Maester Aemon",
    house: "Targaryen",
    gender: "Male",
    age: 102,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/aemon.jpg",
    status: "dead",
    weapon: "Knowledge",
    role: "Maester"
  },
  {
    name: "Alliser Thorne",
    house: "Thorne",
    gender: "Male",
    age: 50,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/alliser.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Nights Watch"
  },
  {
    name: "Janos Slynt",
    house: "Slynt",
    gender: "Male",
    age: 52,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/janos.jpg",
    status: "dead",
    weapon: "Authority",
    role: "Nights Watch"
  },
  {
    name: "Meryn Trant",
    house: "Trant",
    gender: "Male",
    age: 45,
    origin: "Stormlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/meryn.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Knight"
  },
  {
    name: "Illyrio Mopatis",
    house: "None",
    gender: "Male",
    age: 65,
    origin: "Pentos",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/illyrio.jpg",
    status: "alive",
    weapon: "Wealth",
    role: "Others"
  },
  {
    name: "Mace Tyrell",
    house: "Tyrell",
    gender: "Male",
    age: 58,
    origin: "Reach",
    religion: "Faith of the Seven",
    first_seen: "Season 2",
    image: "ımage/mace.jpg",
    status: "dead",
    weapon: "Politics",
    role: "Lord"
  },
  // YENİ EKLENEN 10 KARAKTER
  {
    name: "Rickon Stark",
    house: "Stark",
    gender: "Male",
    age: 10,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/rickon.jpg",
    status: "dead",
    weapon: "Running",
    role: "Highborn"
  },
  {
    name: "Myrcella Baratheon",
    house: "Baratheon",
    gender: "Female",
    age: 16,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/myrcella.jpg",
    status: "dead",
    weapon: "None",
    role: "Highborn"
  },
  {
    name: "Tommen Baratheon",
    house: "Baratheon",
    gender: "Male",
    age: 14,
    origin: "Crownlands",
    religion: "Faith of the Seven",
    first_seen: "Season 4",
    image: "ımage/tommen.jpg",
    status: "dead",
    weapon: "None",
    role: "King"
  },
  {
    name: "Loras Tyrell",
    house: "Tyrell",
    gender: "Male",
    age: 24,
    origin: "Reach",
    religion: "Faith of the Seven",
    first_seen: "Season 1",
    image: "ımage/loras.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Knight"
  },
  {
    name: "Jeor Mormont",
    house: "Mormont",
    gender: "Male",
    age: 68,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/jeor.jpg",
    status: "dead",
    weapon: "Longclaw",
    role: "Nights Watch"
  },
  {
    name: "Benjen Stark",
    house: "Stark",
    gender: "Male",
    age: 42,
    origin: "North",
    religion: "Old Gods",
    first_seen: "Season 1",
    image: "ımage/benjen.jpg",
    status: "dead",
    weapon: "Spear",
    role: "Nights Watch"
  },
  {
    name: "Syrio Forel",
    house: "None",
    gender: "Male",
    age: 50,
    origin: "Braavos",
    religion: "Many-Faced God",
    first_seen: "Season 1",
    image: "ımage/syrio.jpg",
    status: "dead",
    weapon: "Sword",
    role: "Others"
  },
  {
    name: "Qotho",
    house: "Dothraki",
    gender: "Male",
    age: 35,
    origin: "Essos",
    religion: "Great Stallion",
    first_seen: "Season 1",
    image: "ımage/qotho.jpg",
    status: "dead",
    weapon: "Arakh",
    role: "Warrior"
  },
  {
    name: "Kovarro",
    house: "Dothraki",
    gender: "Male",
    age: 30,
    origin: "Essos",
    religion: "Great Stallion",
    first_seen: "Season 2",
    image: "ımage/kovarro.jpg",
    status: "alive",
    weapon: "Arakh",
    role: "Warrior"
  },
  {
    name: "Doreah",
    house: "None",
    gender: "Female",
    age: 22,
    origin: "Lys",
    religion: "None",
    first_seen: "Season 1",
    image: "ımage/doreah.jpg",
    status: "dead",
    weapon: "Seduction",
    role: "Servant"
  }
];

// Oyun için yardımcı fonksiyonlar
function getRandomCharacter() {
  return characters[Math.floor(Math.random() * characters.length)];
}

function normalizeName(name) {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

function findCharacterByName(inputName) {
  const normalizedInput = normalizeName(inputName);
  return characters.find(char => 
    normalizeName(char.name) === normalizedInput ||
    normalizeName(char.name).includes(normalizedInput)
  );
}

function getAutocompleteSuggestions(input) {
  if (!input || input.length < 2) return [];
  const normalizedInput = normalizeName(input);
  return characters
    .filter(char => normalizeName(char.name).includes(normalizedInput))
    .slice(0, 5);
}

// Konsola hata ayıklama için
console.log(`Toplam ${characters.length} karakter yüklendi`);